#permalink: /:title
title: n+e's Blog   # your title
author: n+e # your name
description: Just have some fun here # your description
avatar: /images/avatar.png # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"
gems: [jekyll-paginate]

excerpt_separator: '<!-- more -->'

# Comments
disqus:
  shortname: trinkle   # your disqus shortname

# Google Analytics
# google_analytics:   # your google analytics
